### ISSUE TITLE
Do it support import in component? not globally registered

### ISSUE THREAD

**Issue by hxgqh** [tsparticles/vue3#67]
For example:

```vue
import VueParticles from '@tsparticles/vue3'
```

**Comment by matteobruni** [comment]
Can you elaborate more? I don’t understand the question

**Comment by alex-martinez** [comment]
I understand his question, because I ran into a similar issue. 

The README shows how to globally instantiate the `VueParticles` component, but in my case I don't want this because it bloats the entry file. What I wanted was to simply import the `VueParticles` component  into my component.

What I ended up doing was importing the component directly `import VueParticles from '@tsparticles/vue3/src/components/vue-particles.vue';` and using `https://github.com/tsparticles/vue3/blob/main/components/vue3/src/components/index.ts` as a reference on how to load it.

Probably not the best solution, but it seems to have worked.

```vue
<script setup lang="ts">
import { onBeforeMount } from 'vue';
import { loadSlim } from '@tsparticles/slim';
import type { ISourceOptions } from '@tsparticles/engine';
import { tsParticles } from '@tsparticles/engine';
import VueParticles from '@tsparticles/vue3/src/components/vue-particles.vue';

onBeforeMount(() => {
  tsParticles.init();

  await loadSlim(tsParticles);
  dispatchEvent(new CustomEvent('particlesInit', { detail: tsParticles }));
});

// ...

</script>
```

**Comment by matteobruni** [comment]
> I understand his question, because I ran into a similar issue.
> 
> The README shows how to globally instantiate the `VueParticles` component, but in my case I don't want this because it bloats the entry file. What I wanted was to simply import the `VueParticles` component into my component.
> 
> What I ended up doing was importing the component directly `import VueParticles from '@tsparticles/vue3/src/components/vue-particles.vue';` and using `https://github.com/tsparticles/vue3/blob/main/components/vue3/src/components/index.ts` as a reference on how to load it.
> 
> Probably not the best solution, but it seems to have worked.
> 
> ```
> <script setup lang="ts">
> import { onBeforeMount } from 'vue';
> import { loadSlim } from '@tsparticles/slim';
> import type { ISourceOptions } from '@tsparticles/engine';
> import { tsParticles } from '@tsparticles/engine';
> import VueParticles from '@tsparticles/vue3/src/components/vue-particles.vue';
> 
> onBeforeMount(async () => {
>   tsParticles.init();
> 
>   await loadSlim(tsParticles);
> 
>   /* EDIT: We don't need this actually */
>   // dispatchEvent(new CustomEvent('particlesInit', { detail: tsParticles }));
> });
> 
> // ...
> 
> </script>
> ```

Accessing `src` files is not a recommended solution, since they can be renamed, changed or anything that can break your code. The plugin needs to be installed to setup correctly the particles so every component will benefit a faster initialization and no conflicts on loaded tsParticles plugins. This was a necessary change from v2.

**Comment by riderx** [comment]
@matteobruni Global import is not recommended in vue3.
It breaks the ability to code split, The particle is used only on one page in my project it doesn't make sense to bloat all pages with it.
Can we have an official way to do it ?

**Comment by mstnorris** [comment]
A little late to the party but...

@hxgqh example: Fireworks.vue

**Fireworks.vue**
```
<script setup>
import { onMounted } from "vue";
import { loadFireworksPreset } from "@tsparticles/preset-fireworks";
import { tsParticles } from "@tsparticles/engine";

onMounted(async () => {
  await loadFireworksPreset(tsParticles);

  await tsParticles.load({
    id: "tsparticles",
    options: {
      preset: "fireworks",
    },
  });
})

</script>

<template>
  <div id="app">
    <div id="tsparticles" />
  </div>
</template>
```
